name: Feature
description: Шаблон создания feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: Спасибо, что делаете вклад в наш проект
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: Опишите доработку
    validations:
      required: true
