name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run zip
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*.zip"
        name: ${{github.ref_name}}
        body: ${{steps.build_changelog.outputs.changelog}}
        makeLatest: true
